<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.incresearch.com/Rave/STS"
                xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:rl="http://soa.incresearch.com/Rave/URL"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveODM.xsd"/>
        <oracle-xsl-mapper:rootElement name="ODM" namespace="http://www.cdisc.org/ns/odm/v1.3"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveSTS.xsd"/>
        <oracle-xsl-mapper:rootElement name="Subject" namespace="http://soa.incresearch.com/Rave/STS"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 07 03:50:52 EDT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="TarSite">
      <xsl:choose>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5005">
          <xsl:value-of select="number(7004)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5016">
          <xsl:value-of select="number(7008)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5007">
          <xsl:value-of select="number(7015)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5026">
          <xsl:value-of select="number(7016)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5022">
          <xsl:value-of select="number(7021)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5012">
          <xsl:value-of select="number(7023)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5021">
          <xsl:value-of select="number(7024)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5010">
          <xsl:value-of select="number(7026)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5027">
          <xsl:value-of select="number(7029)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5011">
          <xsl:value-of select="number(7031)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5033">
          <xsl:value-of select="number(7032)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5013">
          <xsl:value-of select="number(7033)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5001">
          <xsl:value-of select="number(7034)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5015">
          <xsl:value-of select="number(7035)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5008">
          <xsl:value-of select="number(7037)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5020">
          <xsl:value-of select="number(7038)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5009">
          <xsl:value-of select="number(7041)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5032">
          <xsl:value-of select="number(7043)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5004">
          <xsl:value-of select="number(7044)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5018">
          <xsl:value-of select="number(7047)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5003">
          <xsl:value-of select="number(7048)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5025">
          <xsl:value-of select="number(7054)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5019">
          <xsl:value-of select="number(7056)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5030">
          <xsl:value-of select="number(7057)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5043">
          <xsl:value-of select="number(7058)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5042">
          <xsl:value-of select="number(7059)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5035">
          <xsl:value-of select="number(7066)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5002">
          <xsl:value-of select="number(7067)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5029">
          <xsl:value-of select="number(7071)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5028">
          <xsl:value-of select="number(7072)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5047">
          <xsl:value-of select="number(7073)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5017">
          <xsl:value-of select="number(7074)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5045">
          <xsl:value-of select="number(7075)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5023">
          <xsl:value-of select="number(7078)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5044">
          <xsl:value-of select="number(7079)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5034">
          <xsl:value-of select="number(7082)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5031">
          <xsl:value-of select="number(7084)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5046">
          <xsl:value-of select="number(7087)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5040">
          <xsl:value-of select="number(7097)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5037">
          <xsl:value-of select="number(7102)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5036">
          <xsl:value-of select="number(7103)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5041">
          <xsl:value-of select="number(7104)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5039">
          <xsl:value-of select="number(7109)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5207">
          <xsl:value-of select="number(7110)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5203">
          <xsl:value-of select="number(7111)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5204">
          <xsl:value-of select="number(7112)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5202">
          <xsl:value-of select="number(7113)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5206">
          <xsl:value-of select="number(7114)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5205">
          <xsl:value-of select="number(7115)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5110">
          <xsl:value-of select="number(7116)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5112">
          <xsl:value-of select="number(7118)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5111">
          <xsl:value-of select="number(7119)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5109">
          <xsl:value-of select="number(7120)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5107">
          <xsl:value-of select="number(7131)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5141">
          <xsl:value-of select="number(7132)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5108">
          <xsl:value-of select="number(7133)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5140">
          <xsl:value-of select="number(7134)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5146">
          <xsl:value-of select="number(7169)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5145">
          <xsl:value-of select="number(7171)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5147">
          <xsl:value-of select="number(7172)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5125">
          <xsl:value-of select="number(7175)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5133">
          <xsl:value-of select="number(7176)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5120">
          <xsl:value-of select="number(7177)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5126">
          <xsl:value-of select="number(7178)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5138">
          <xsl:value-of select="number(7179)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5123">
          <xsl:value-of select="number(7180)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5127">
          <xsl:value-of select="number(7181)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5128">
          <xsl:value-of select="number(7183)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5124">
          <xsl:value-of select="number(7184)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5136">
          <xsl:value-of select="number(7185)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5122">
          <xsl:value-of select="number(7186)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5102">
          <xsl:value-of select="number(7187)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5139">
          <xsl:value-of select="number(7188)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5106">
          <xsl:value-of select="number(7189)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5131">
          <xsl:value-of select="number(7190)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5132">
          <xsl:value-of select="number(7191)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5103">
          <xsl:value-of select="number(7192)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5105">
          <xsl:value-of select="number(7194)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5135">
          <xsl:value-of select="number(7195)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5104">
          <xsl:value-of select="number(7196)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5137">
          <xsl:value-of select="number(7197)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5134">
          <xsl:value-of select="number(7198)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5130">
          <xsl:value-of select="number(7201)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5121">
          <xsl:value-of select="number(7202)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5129">
          <xsl:value-of select="number(7203)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5101">
          <xsl:value-of select="number(7215)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5118">
          <xsl:value-of select="number(7216)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5116">
          <xsl:value-of select="number(7217)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5117">
          <xsl:value-of select="number(7218)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5115">
          <xsl:value-of select="number(7219)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =5119">
          <xsl:value-of select="number(7220)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <tns:Subject>
      <tns:Details>
        <tns:sourceSubjectKey>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey"/>
        </tns:sourceSubjectKey>
        <tns:sourceLocationOID>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID"/>
        </tns:sourceLocationOID>
        <tns:targetSubjectKey>
          <xsl:value-of select="concat($TarSite,'-',/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID,substring(/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey,string-length(/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey)-1))"/>
        </tns:targetSubjectKey>
        <tns:targetLocationOID>
          <xsl:value-of select="$TarSite"/>
        </tns:targetLocationOID>
        <tns:transfer>1</tns:transfer>
      </tns:Details>
    </tns:Subject>
  </xsl:template>
</xsl:stylesheet>