<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:java="http://www.oracle.com/XSL/Transform/java/java.lang.String"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.cdisc.org/ns/odm/v1.3"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://soa.incresearch.com/Rave/STS"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/RaveSTSPOC/DemoStudyTFM/DemoStudyBPELProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://soa.incresearch.com/Rave/URL"
                xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:fn="http://www.w3.org/2005/xpath-functions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveSTS.xsd"/>
        <oracle-xsl-mapper:rootElement name="Subject" namespace="http://soa.incresearch.com/Rave/STS"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveODM.xsd"/>
        <oracle-xsl-mapper:rootElement name="ODM" namespace="http://www.cdisc.org/ns/odm/v1.3"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED Jun 03 01:28:27 EDT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ODM FileType="Transactional" FileOID="{/ns0:Subject/tns:ODM/@FileOID}"
             CreationDateTime="{/ns0:Subject/tns:ODM/@CreationDateTime}"
             ODMVersion="{/ns0:Subject/tns:ODM/@ODMVersion}">
      <xsl:for-each select="/ns0:Subject/tns:ODM/tns:ClinicalData">
        <xsl:if test='tns:SubjectData/tns:StudyEventData/@StudyEventOID = "SUBJECT" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="EN" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="HT" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="VS" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="PE" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="HEM" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="CHEM" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="URIN" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="UPREG" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "W52" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="PK" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "SCRN" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="DM" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "AE" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="AE" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "CNMED" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="PCMEDN" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "CNMEDM" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="PCM" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "ADT" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="ADT" or tns:SubjectData/tns:StudyEventData/@StudyEventOID = "SCRN" and tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID ="MH"'>
          <!-- above added all forms and folders conditions as per spec to this condition so that this doesn't create unnecessary clinical data -->
          <tns:ClinicalData MetaDataVersionOID="{@MetaDataVersionOID}"
                            StudyOID="{/ns0:Subject/ns1:RaveUrls/ns1:RaveUrl[@utype='TARGET']/ns1:studyName}">
            <tns:SubjectData TransactionType="Update">
              <xsl:attribute name="SubjectKey">
                <xsl:value-of select="/ns0:Subject/ns0:Details/ns0:targetSubjectKey"/>
              </xsl:attribute>
              <tns:SiteRef LocationOID="{/ns0:Subject/ns0:Details/ns0:targetLocationOID}"/>
              <!-- SUBJECT CONFIG-->
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'SUBJECT')and   (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='EN'))">
                <tns:StudyEventData StudyEventOID="SUBJECT">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:attribute name="TransactionType">Upsert</xsl:attribute>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">EN</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='EN.SUBNUM1')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">EN.SUBNUM1</xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="concat (/ns0:Subject/ns0:Details/ns0:sourceLocationOID, substring(@Value, string-length(@Value)-1) )"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:attribute name="TransactionType">Update</xsl:attribute>
                            </tns:ItemData>
                            <tns:ItemData ItemOID="EN.PTRIAL" Value="3" TransactionType="Update" mdsol:Lock="AsFound"/>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='VS'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">VS</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'VS','VS')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='VS.TEMP') or ( @ItemOID='VS.TEMPU') or (@ItemOID='VS.RECGUID') or  (@ItemOID='VS.TEMPND') or  (@ItemOID='VS.RESP') or  (@ItemOID='VS.RESPND') or  (@ItemOID='VS.PULSE') or  (@ItemOID='VS.PULSEND') or  (@ItemOID='VS.SYSBP') or  (@ItemOID='VS.DIABP') or  (@ItemOID='VS.BPND') or  (@ItemOID='VS.HT') or  (@ItemOID='VS.HTU') or  (@ItemOID='VS.HTND') or  (@ItemOID='VS.WT') or  (@ItemOID='VS.WTU') or  (@ItemOID='VS.WTND')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('VS.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='VS.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='PE'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">PE</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'PE','PE')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='PE.PEYN') or (@ItemOID='PE.RECGUID') or  (@ItemOID='PE.PEDAT') or  (@ItemOID='PE.PEBSYS') or  (@ItemOID='PE.PEND') or  (@ItemOID='PE.PEXAM') or  (@ItemOID='PE.PECLINSG') or  (@ItemOID='PE.OTHSP')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('PE.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='PE.BODYSYS')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='HEM'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">HEM</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'HEM','HEM')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='HEM.HEMYN') or (@ItemOID='HEM.RECGUID') or  (@ItemOID='HEM.HEMDAT') or  (@ItemOID='HEM.HEMRAN')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('HEM.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='HEM.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='CHEM'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">CHEM</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'CHEM','CHEM')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='CHEM.CHEMYN') or (@ItemOID='CHEM.RECGUID') or  (@ItemOID='CHEM.CHEMDAT') or  (@ItemOID='CHEM.CHEMRAN')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('CHEM.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='CHEM.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='URIN'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">URIN</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'URIN','URIN')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='URIN.URINYN') or (@ItemOID='URIN.RECGUID') or  (@ItemOID='URIN.URINDAT') or  (@ItemOID='URIN.URINRAN')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('URIN.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='URIN.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='UPREG'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">UPREG</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'UPREG','UPREG')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='UPREG.UPRGYN') or (@ItemOID='UPREG.RECGUID') or  (@ItemOID='UPREG.UPRGDAT') or  (@ItemOID='UPREG.UPRGRES')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('UPREG.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='UPREG.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='PK'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:attribute name="FormOID">PK</xsl:attribute>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'PK','PK')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='PK.PKDAT') or (@ItemOID='PK.RECGUID') or  (@ItemOID='PK.PKTM') or  (@ItemOID='PK.PKND')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('PK.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='PK.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'W52')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='HT'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:attribute name="FormOID">HT</xsl:attribute>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'HT','HT')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='HT.HTYN') or (@ItemOID='HT.DAT') or  (@ItemOID='HT.HTRAN') or (@ItemOID='HT.RECGUID')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('HT.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='HT.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'SCRN')and (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='DM'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">DM</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'DM','DM')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='DM.BRTHDAT') or ( @ItemOID='DM.BIRTHY') or (@ItemOID='DM.RECGUID') or  (@ItemOID='DM.AGEY') or  (@ItemOID='DM.AGEG') or  (@ItemOID='DM.SEX')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('DM.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='DM.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'AE')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='AE'))">
                <tns:StudyEventData StudyEventOID="AE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">AE</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'AE','AE')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='AE.AEYN') or (@ItemOID='AE.RECGUID') or  (@ItemOID='AE.AETERM') or  (@ItemOID='AE.AESI') or  (@ItemOID='AE.AEISA') or  (@ItemOID='AE.AESTDAT') or  (@ItemOID='AE.AEONGO') or  (@ItemOID='AE.AESPDAT') or  (@ItemOID='AE.AESER') or  (@ItemOID='AE.AECN') or  (@ItemOID='AE.AESD') or  (@ItemOID='AE.AEDTH') or  (@ItemOID='AE.AEIPH') or  (@ItemOID='AE.AELTH') or  (@ItemOID='AE.AEOTH') or  (@ItemOID='AE.AEDTHDAT') or  (@ItemOID='AE.AESEV') or  (@ItemOID='AE.AEREL') or  (@ItemOID='AE.AEACT') or  (@ItemOID='AE.AENONE') or  (@ItemOID='AE.AECNMD') or  (@ItemOID='AE.AEPROC') or  (@ItemOID='AE.AEWTH') or  (@ItemOID='AE.AEOTH1') or  (@ItemOID='AE.OTHSP') or  (@ItemOID='AE.AEOUT')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('AE.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='AE.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'CNMED')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='PCMEDN'))">
                <tns:StudyEventData StudyEventOID="CP">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">PCMEDN</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'PCMEDN','PCMEDN')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='PCMEDN.PCNMEDYN') or (@ItemOID='PCMEDN.RECGUID') or  (@ItemOID='PCMEDN.PCMPROC') or  (@ItemOID='PCMEDN.INDC') or  (@ItemOID='PCMEDN.PCMSTDAT') or  (@ItemOID='PCMEDN.PCMUNK') or  (@ItemOID='PCMEDN.PCMENDAT') or  (@ItemOID='PCMEDN.PCMONG')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('PCMEDN.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='PCMEDN.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'CNMEDM')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='PCM'))">
                <tns:StudyEventData StudyEventOID="CM">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">PCM</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'PCM','PCM')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='PCM.PCMYN') or (@ItemOID='PCM.RECGUID') or  (@ItemOID='PCM.PCMTERM') or  (@ItemOID='PCM.PCMINDC')  or  (@ItemOID='PCM.PCMPTHSP') or  (@ItemOID='PCM.PCMDOS') or  (@ItemOID='PCM.PCMDOSU') or  (@ItemOID='PCM.DOSUSP') or  (@ItemOID='PCM.PCMFREQ') or  (@ItemOID='PCM.FREQSP') or  (@ItemOID='PCM.PCMROUTE') or  (@ItemOID='PCM.ROUTESP') or  (@ItemOID='PCM.PCMSTDAT') or  (@ItemOID='PCM.PCMSTUNK') or  (@ItemOID='PCM.PCMENDAT') or  (@ItemOID='PCM.PCMONGO')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('PCM.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='PCM.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'ADT')and                (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='ADT'))">
                <tns:StudyEventData StudyEventOID="ADT">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">ADT</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'ADT','ADT')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='ADT.ADTYN') or (@ItemOID='ADT.RECGUID') or  (@ItemOID='ADT.ADTERM') or  (@ItemOID='ADT.ADTIND') or  (@ItemOID='ADT.ADTDOSE') or  (@ItemOID='ADT.ADTDOSU') or  (@ItemOID='ADT.OTHSP') or  (@ItemOID='ADT.ADTFRQ') or  (@ItemOID='ADT.OTHSP1') or  (@ItemOID='ADT.ADTROUTE') or  (@ItemOID='ADT.OTHSP2') or (@ItemOID='ADT.ADTSTDAT') or  (@ItemOID='ADT.ADTENDAT') or  (@ItemOID='ADT.ADTONG')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('ADT.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='ADT.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
              <xsl:if test="((tns:SubjectData/tns:StudyEventData/@StudyEventOID = 'SCRN')and (tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID='MH'))">
                <tns:StudyEventData StudyEventOID="BASE">
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey">
                    <xsl:attribute name="StudyEventRepeatKey">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@StudyEventRepeatKey"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="tns:SubjectData/tns:StudyEventData/@TransactionType">
                    <xsl:attribute name="TransactionType">
                      <xsl:value-of select="tns:SubjectData/tns:StudyEventData/@TransactionType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="not(tns:SubjectData/tns:StudyEventData/@TransactionType)">
                    <xsl:attribute name="TransactionType">Update</xsl:attribute>
                  </xsl:if>
                  <tns:FormData>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormOID">
                      <xsl:attribute name="FormOID">MH</xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey">
                      <xsl:attribute name="FormRepeatKey">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@FormRepeatKey"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType">
                      <xsl:attribute name="TransactionType">
                        <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/@TransactionType)">
                      <xsl:attribute name="TransactionType">Update</xsl:attribute>
                    </xsl:if>
                    <tns:ItemGroupData>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID">
                        <xsl:attribute name="ItemGroupOID">
                          <xsl:value-of select="java:replaceAll(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupOID,'MH','BASE')"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey">
                        <xsl:attribute name="ItemGroupRepeatKey">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@ItemGroupRepeatKey"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType">
                        <xsl:attribute name="TransactionType">
                          <xsl:value-of select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="not(tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/@TransactionType)">
                        <xsl:attribute name="TransactionType">Update</xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="tns:SubjectData/tns:StudyEventData/tns:FormData/tns:ItemGroupData/tns:ItemData">
                        <xsl:choose>
                          <xsl:when test="( @ItemOID='MH.MHYN') or (@ItemOID='MH.RECGUID') or  (@ItemOID='MH.MHASTHYN') or  (@ItemOID='MH.MHALLYN') or  (@ItemOID='MH.MHTERM') or  (@ItemOID='MH.MHSTDAT') or  (@ItemOID='MH.MHSDUNK') or  (@ItemOID='MH.MHENDAT') or  (@ItemOID='MH.MHENUNK') or  (@ItemOID='MH.MHONGO')">
                            <tns:ItemData mdsol:Lock="AsFound">
                              <xsl:if test="@ItemOID">
                                <xsl:attribute name="ItemOID">
                                  <xsl:value-of select="concat('MH.',substring-after(@ItemOID,'.'))"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@Value">
                                <xsl:attribute name="Value">
                                  <xsl:value-of select="@Value"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="@IsNull">
                                <xsl:attribute name="IsNull">
                                  <xsl:value-of select="@IsNull"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:choose>
                                <xsl:when test="(@ItemOID='BASE.RECGUID')">
                                  <xsl:attribute name="TransactionType">Context</xsl:attribute>
                                </xsl:when>
                                <xsl:otherwise>
                                  <xsl:attribute name="TransactionType">Update</xsl:attribute>
                                </xsl:otherwise>
                              </xsl:choose>
                              <xsl:value-of select="."/>
                            </tns:ItemData>
                          </xsl:when>
                        </xsl:choose>
                      </xsl:for-each>
                    </tns:ItemGroupData>
                  </tns:FormData>
                </tns:StudyEventData>
              </xsl:if>
            </tns:SubjectData>
          </tns:ClinicalData>
        </xsl:if>
      </xsl:for-each>
    </tns:ODM>
  </xsl:template>
</xsl:stylesheet>