<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://www.cdisc.org/ns/odm/v1.3"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://soa.incresearch.com/Rave/STS"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl"
                xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:rl="http://soa.incresearch.com/Rave/URL"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveODM.xsd"/>
        <oracle-xsl-mapper:rootElement name="ODM" namespace="http://www.cdisc.org/ns/odm/v1.3"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/RaveSTS.xsd"/>
        <oracle-xsl-mapper:rootElement name="Subject" namespace="http://soa.incresearch.com/Rave/STS"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 07 03:50:52 EDT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="TarSite">
      <xsl:choose>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4014">
          <xsl:value-of select="number(7001)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4004">
          <xsl:value-of select="number(7002)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4003">
          <xsl:value-of select="number(7003)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4011">
          <xsl:value-of select="number(7005)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4026">
          <xsl:value-of select="number(7006)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4024">
          <xsl:value-of select="number(7007)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4009">
          <xsl:value-of select="number(7009)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4001">
          <xsl:value-of select="number(7011)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4017">
          <xsl:value-of select="number(7012)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4019">
          <xsl:value-of select="number(7013)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4016">
          <xsl:value-of select="number(7014)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4031">
          <xsl:value-of select="number(7018)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4012">
          <xsl:value-of select="number(7019)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4015">
          <xsl:value-of select="number(7020)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4002">
          <xsl:value-of select="number(7022)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4010">
          <xsl:value-of select="number(7025)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4018">
          <xsl:value-of select="number(7027)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4023">
          <xsl:value-of select="number(7028)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4028">
          <xsl:value-of select="number(7030)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4013">
          <xsl:value-of select="number(7036)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4008">
          <xsl:value-of select="number(7039)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4033">
          <xsl:value-of select="number(7040)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4032">
          <xsl:value-of select="number(7042)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4006">
          <xsl:value-of select="number(7045)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4021">
          <xsl:value-of select="number(7046)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4022">
          <xsl:value-of select="number(7068)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4007">
          <xsl:value-of select="number(7069)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4027">
          <xsl:value-of select="number(7086)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4025">
          <xsl:value-of select="number(7091)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4030">
          <xsl:value-of select="number(7092)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4040">
          <xsl:value-of select="number(7096)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4038">
          <xsl:value-of select="number(7099)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4039">
          <xsl:value-of select="number(7100)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4037">
          <xsl:value-of select="number(7105)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4036">
          <xsl:value-of select="number(7106)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4141">
          <xsl:value-of select="number(7121)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4137">
          <xsl:value-of select="number(7122)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4135">
          <xsl:value-of select="number(7123)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4138">
          <xsl:value-of select="number(7124)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4114">
          <xsl:value-of select="number(7125)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4129">
          <xsl:value-of select="number(7126)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4136">
          <xsl:value-of select="number(7127)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4116">
          <xsl:value-of select="number(7128)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4121">
          <xsl:value-of select="number(7136)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4101">
          <xsl:value-of select="number(7138)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4112">
          <xsl:value-of select="number(7141)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4119">
          <xsl:value-of select="number(7143)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4115">
          <xsl:value-of select="number(7144)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4113">
          <xsl:value-of select="number(7146)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4102">
          <xsl:value-of select="number(7147)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4117">
          <xsl:value-of select="number(7150)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4111">
          <xsl:value-of select="number(7155)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4125">
          <xsl:value-of select="number(7156)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4133">
          <xsl:value-of select="number(7157)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4118">
          <xsl:value-of select="number(7158)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4126">
          <xsl:value-of select="number(7160)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4143">
          <xsl:value-of select="number(7161)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4124">
          <xsl:value-of select="number(7162)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4109">
          <xsl:value-of select="number(7163)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4108">
          <xsl:value-of select="number(7164)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4103">
          <xsl:value-of select="number(7165)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4105">
          <xsl:value-of select="number(7166)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4122">
          <xsl:value-of select="number(7167)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4142">
          <xsl:value-of select="number(7204)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4130">
          <xsl:value-of select="number(7205)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4132">
          <xsl:value-of select="number(7206)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4104">
          <xsl:value-of select="number(7207)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4131">
          <xsl:value-of select="number(7208)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4120">
          <xsl:value-of select="number(7210)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4134">
          <xsl:value-of select="number(7211)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4128">
          <xsl:value-of select="number(7212)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4123">
          <xsl:value-of select="number(7213)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4106">
          <xsl:value-of select="number(7214)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4237">
          <xsl:value-of select="number(7243)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4230">
          <xsl:value-of select="number(7245)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4228">
          <xsl:value-of select="number(7246)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4203">
          <xsl:value-of select="number(7247)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4206">
          <xsl:value-of select="number(7248)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4234">
          <xsl:value-of select="number(7249)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4236">
          <xsl:value-of select="number(7250)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4204">
          <xsl:value-of select="number(7251)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4235">
          <xsl:value-of select="number(7252)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4233">
          <xsl:value-of select="number(7253)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4231">
          <xsl:value-of select="number(7254)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4232">
          <xsl:value-of select="number(7255)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4202">
          <xsl:value-of select="number(7256)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4205">
          <xsl:value-of select="number(7257)"/>
        </xsl:when>
        <xsl:when test="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID =4215">
          <xsl:value-of select="number(7259)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <tns:Subject>
      <tns:Details>
        <tns:sourceSubjectKey>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey"/>
        </tns:sourceSubjectKey>
        <tns:sourceLocationOID>
          <xsl:value-of select="/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID"/>
        </tns:sourceLocationOID>
        <tns:targetSubjectKey>
          <xsl:value-of select="concat($TarSite,'-',/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/ns0:SiteRef/@LocationOID,substring(/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey,string-length(/ns0:ODM/ns0:ClinicalData/ns0:SubjectData/@SubjectKey)-1))"/>
        </tns:targetSubjectKey>
        <tns:targetLocationOID>
          <xsl:value-of select="$TarSite"/>
        </tns:targetLocationOID>
        <tns:transfer>1</tns:transfer>
      </tns:Details>
    </tns:Subject>
  </xsl:template>
</xsl:stylesheet>
